DROP TABLE IF EXISTS vehicle
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS departure;
DROP TABLE IF EXISTS arrival;

CREATE TABLE vehicle (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	year INTEGER NOT NULL,
	make TEXT NOT NULL,
	model TEXT NOT NULL,
	motor TEXT NOT NULL,
	vin TEXT NOT NULL
);

CREATE TABLE location (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	name TEXT NOT NULL,
	dateOfBirth DATE NOT NULL
);

CREATE TABLE service (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	vehicleId INTEGER NOT NULL,
	userId INTEGER NOT NULL,
	status TEXT NOT NULL
);

CREATE TABLE departure (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	serviceId INTEGER NOT NULL,
	locationId INTEGER NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	totalKm INTEGER NOT NULL
);

CREATE TABLE arrival (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	serviceId INTEGER NOT NULL,
	locationId INTEGER NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	totalKm INTEGER NOT NULL
	);

